export default {
  GET_PROFILES_LIST_URL: 'http://localhost:3000/resource/profile/registry.json',

  REQUEST_PROFILE_DATA: 'REQUEST_PROFILE_DATA',
  RECEIVE_PROFILE_DATA: 'RECEIVE_PROFILE_DATA',
  FILTER_PROFILE_DATA: 'FILTER_PROFILE_DATA',
  SORT_PROFILE_DATA: 'SORT_PROFILE_DATA',
  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  RESET_ERROR_MESSAGE: 'RESET_ERROR_MESSAGE',
}
